### PR TITLE
Fix SPI mode (should be CPOL = 0, CPHA = 0)

### LINKED ISSUE #4: Inverted clock polarity does not seem to work?
cc @therealprof, not sure whats going on here

I tested version v3 out on real hardware (ItsyBitsy M4). I was not able to get it working with the end frame polarity inverted - it would twitch blue and pink.

I could only get it working if I reset clock polarity back to all ones (0xff), which is no longer the default configuration.

This doesnt match my expectations.

Any chance you can try out the behaviour in v3 @therealprof ? would be interested to know how it behaves for your setup + if we can track down what its doing.

### PR DESCRIPTION
**Pull request by twitchyliquid64**
Fixes #4

### CODE REVIEW

**Comment by sajattack** [comment]
Citation needed.

**Comment by twitchyliquid64** [comment]
Have a look at the first logic analyzer capture: https://cpldcpu.wordpress.com/2014/11/30/understanding-the-apa102-superled/

Page 4 of the datasheet seems to show the rising edge of the clock: https://cdn-shop.adafruit.com/datasheets/APA102.pdf

Adafruit's library sets it to mode 0: https://github.com/adafruit/Adafruit_DotStar/blob/master/Adafruit_DotStar.cpp#L188

**Comment by therealprof** [comment]
@twitchyliquid64 I thought this SPI mode didn't work for you either?

**Comment by twitchyliquid64** [comment]
@therealprof I found a bug in the SPI HAL I was using.

**Comment by therealprof** [comment]
Oh, good to know.

**Pull request merged**
